R12/T04/feature/dropdown_confirmation merge pull request
thaisclxt/proj-sist-2021-2 pull request #21
Opened 2021-11-10 01:49 UTC by alineralncs

2021-11-10 21:11 UTC, thaisclxt requested changes
Comentários no código para algumas correções.

Pull Request **reprovado**!

2021-11-10 21:11 UTC, thaisclxt commented on lib/app/modules/restaurant_home/components/update_profile/update_profile_dropdown.dart
> +      Modular.get<RestaurantRegisterStore>();
Você está usando o MobX de forma errada. Ao invés de instanciar de `RestaurantRegisterStore`, que é para registro, instancie de `RestaurantHomeStore`, que é referente à página home da loja. Assim, toda a parte de mudança de estado do dropdown deve estar em `lib/app/modules/restaurant_home/restaurant_home_store.dart`.

2021-11-11 02:32 UTC, alineralncs commented on lib/app/modules/restaurant_home/components/update_profile/update_profile.dart
> +import 'package:pscomidas/app/modules/restaurant_home/components/update_profile/update_profile_dropdown.dart';
ok

2021-11-11 02:32 UTC, alineralncs commented on lib/app/modules/restaurant_home/components/update_profile/update_profile_dropdown.dart
> +import 'package:flutter/services.dart';
ok

2021-11-11 02:34 UTC, alineralncs commented on lib/app/modules/restaurant_home/components/update_profile/update_profile_dropdown.dart
> +          ),
Pra resolver esse problema e o problema anterior eu criei um novo arquivo update_profile_c_button com a classe UpdateProfileConfirmationButton e instanciei em update_profile.

2021-11-11 02:34 UTC, alineralncs commented on lib/app/modules/restaurant_home/components/update_profile/update_profile_dropdown.dart
> +import 'package:pscomidas/app/modules/restaurant_register/restaurant_register_page.dart';
ok

2021-11-11 03:15 UTC, alineralncs commented on lib/app/modules/restaurant_home/components/update_profile/update_profile_dropdown.dart
> +      Modular.get<RestaurantRegisterStore>();
Ok

2021-11-11 19:03 UTC, thaisclxt requested changes
Ao selecionar uma categoria diferente de _Açaí_, o valor não está sendo modificado no estado. 
Isso está acontecendo porque você modificou o arquivo `restaurant_home_store.dart`, porém o arquivo `restaurant_home_store.g.dart` não sofreu alteração.
Execute o comando `flutter pub run build_runner build`, com atenção. Caso apareça algum erro, ou conflito, corrija. Ele irá dizer o que deve ser feito.

Pull request **reprovada**.

2021-11-11 19:14 UTC, thaisclxt commented
Pull Request fechada porque não é para enviar para a branch `develop` e sim para `R12`.

2021-11-11 19:14 UTC, closed without merging