T05/feature/mobx
thaisclxt/proj-sist-2021-2 pull request #22
Opened 2021-11-11 18:02 UTC by mdmundo

Além de mover duas variáveis para o `restaurant_home_store.dart`. Este _pull request_ contém a formatação de outros arquivos.

2021-11-11 20:54 UTC, thaisclxt reviewed
Ao meu ver está tudo okay e o Pull Request pode ser **aprovado**.
Aguardando a revisão do @nathans4ntos.

2021-11-11 23:09 UTC, nathans4ntos commented
Os controllers do campos deveriam estar unidos na Store em um só, para facilitar o envio de dados para o firebase.

<img width="687" alt="Captura de Tela 2021-11-11 às 19 31 29" src="https://user-images.githubusercontent.com/54455848/141378502-fd846b91-37ba-4263-8124-2f3e71131f35.png">
<img width="536" alt="Captura de Tela 2021-11-11 às 19 31 37" src="https://user-images.githubusercontent.com/54455848/141378524-09df86c6-d9e3-4d78-ab83-4515eb555b54.png">

2021-11-15 22:49 UTC, nathans4ntos requested changes
Devido a isto, considero a Pull Request **REPROVADA** até as correções solicitadas serem atendidas.

2021-11-15 22:49 UTC, nathans4ntos commented on lib/app/modules/restaurant_home/components/update_profile/update_formulary.dart
> +              Observer(builder: (cxt) {
Uso desnecessário do Observer no form.

2021-11-15 22:49 UTC, nathans4ntos commented on lib/app/modules/restaurant_home/components/update_profile/update_formulary.dart
> +              Observer(builder: (cxt) {
Uso desnecessário do Observer no form.

2021-11-15 22:49 UTC, nathans4ntos commented on lib/app/modules/restaurant_home/components/update_profile/update_formulary.dart
> +                Observer(builder: (cxt) {
Uso desnecessário do Observer no form.

2021-11-16 01:39 UTC, merged