RW01/T06/feature/cupons merge pull request
thaisclxt/proj-sist-2021-2 pull request #40
Opened 2021-12-06 02:54 UTC by nathans4ntos

2021-12-06 14:18 UTC, Ericboo commented on lib/app/global/utils/schemas.dart
> +const cupomTextCollor = Color(0xFF2e6788);
Corrija o nome da variável para ...Color no lugar de ...Collor.

2021-12-06 14:39 UTC, Ericboo requested changes
Alguns aspectos menores do código são passíveis de correção, mas ademais considero o pull request **REPROVADO** especificamente pela seguinte falha visual: 

![image](https://user-images.githubusercontent.com/59875728/144864612-034ba7d9-beab-4dc7-82d3-3af318f9966e.png)

A imagem acima demonstra o resultado de inserir um cupom de desconto ao restaurante. A imagem abaixo demonstra o resultado esperado. 

![image](https://user-images.githubusercontent.com/59875728/144864687-2baa2693-1333-42b7-a1d8-8b792925f7c5.png)

2021-12-06 14:40 UTC, Ericboo commented on lib/app/global/utils/schemas.dart
> +const cupomTextCollor = Color(0xFF2e6788);
Corrija o nome das variáveis de ...Collor para ...Color.

2021-12-06 14:41 UTC, Ericboo commented on lib/app/modules/home/components/cupom/cupom_card.dart
> +        color: const Color(0xFF2e6788),
Para utilizar hexadecimal como cor, adicione-a no schema.

2021-12-06 14:41 UTC, Ericboo commented on lib/app/modules/home/components/cupom/cupom_card.dart
> +          color: const Color(0xFF2e6788), height: 15);
Para utilizar hexadecimal como cor, adicione-a no schema.

2021-12-06 14:42 UTC, Ericboo commented on lib/app/modules/home/schemas.dart
> +const cupomTextCollor = Color(0xFF2e6788);
O arquivo schemas da home é antiquado e passível de exclusão. Utilize o schemas da pasta global.

2021-12-06 15:05 UTC, Ericboo approved these changes

2021-12-07 00:43 UTC, thaisclxt requested changes
Adicionei comentários no código para serem corrigidos. Além deles, ao clicar em cupons pela primeira vez o cupom atual não está na cor desejada, seria interessante deixar secondaryColor, como acontece nos planos.

![image](https://user-images.githubusercontent.com/62521620/144945139-7ce99ba1-d7a4-43da-9fec-6047f767b3d2.png)

Portanto, pull request reprovado.

2021-12-07 00:43 UTC, thaisclxt commented on lib/app/modules/home/components/cupom/cupom_card.dart
> +// Quando não há nenhum cupom o map é do tipo {"tipo": "nenhum"}
Corrigir os restaurantes que estão no banco de dados sem o map do tipo null e cadastrar esse novo tipo no registro de restaurante. Ou seja, assim que um novo restaurante é cadastrado, ele já é cadastrado com o cupom {"tipo": "nenhum"}

![image](https://user-images.githubusercontent.com/62521620/144943535-6ce569ee-d54c-4435-87ab-e0e769804e04.png)

2021-12-07 00:43 UTC, thaisclxt commented on lib/app/modules/home/components/restaurant_card.dart
> +                            restaurant.cupom?['tipo'] != 'nenhum'
Se você corrigir o que eu comentei no comentário de cima, não será necessário fazer estas duas verificações, sendo apenas uma.

2021-12-07 00:43 UTC, thaisclxt commented on lib/app/modules/restaurant_home/pages/cupons/components/cupom_card.dart
> +import 'cupom_selector.dart';
Converta a importação para 'package:'

2021-12-07 13:50 UTC, thaisclxt approved these changes

2021-12-07 13:50 UTC, merged